name: Build and publish Pipeline
on:
  workflow_dispatch:
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    name: build and publish
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23'

      - name: Show Go version
        run: go version

      - name: Remove all Go caches
        run: |
          rm -rf $GOPATH/pkg/mod
          rm -rf ~/.cache/go-build
          go clean -cache -modcache -testcache -x

      - name: Build
        run: make

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: tcld
